// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BetInfoDialog: typeof import('./../components/Lottery/betInfoDialog.vue')['default']
    ChatDialog: typeof import('./../components/ChatDialog/index.vue')['default']
    ChatIframe: typeof import('./../components/ChatIframe/index.vue')['default']
    DraggableChat: typeof import('./../components/DraggableChat/index.vue')['default']
    FloatingService: typeof import('./../components/FloatingService/index.vue')['default']
    FollowActivityModal: typeof import('./../components/FollowActivityModal/index.vue')['default']
    FollowUp: typeof import('./../components/follow-up/index.vue')['default']
    GameCard: typeof import('./../components/GameCard/index.vue')['default']
    GameShare: typeof import('./../components/GameShare/index.vue')['default']
    HistoryBet: typeof import('./../components/follow-up/historyBet.vue')['default']
    K3: typeof import('./../components/Lottery/k3.vue')['default']
    K3trend: typeof import('./../components/follow-up/k3trend.vue')['default']
    Lottery5d: typeof import('./../components/Lottery/lottery5d.vue')['default']
    LotteryReuslt: typeof import('./../components/follow-up/lotteryReuslt.vue')['default']
    NavBar: typeof import('./../components/NavBar/index.vue')['default']
    NicknameDialog: typeof import('./../components/NicknameDialog/index.vue')['default']
    RecentBet: typeof import('./../components/follow-up/recentBet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./../components/Share/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Tabbar: typeof import('./../components/Tabbar/index.vue')['default']
    Trend: typeof import('./../components/follow-up/trend.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanStepper: typeof import('vant/es')['Stepper']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    Win: typeof import('./../components/Lottery/win.vue')['default']
  }
}
